### ISSUE TITLE
End with hyphen?

### ISSUE THREAD

**Issue by andy-ms** [shinnn/github-username-regex#1]
It looks like at least one GitHub username ends with a hyphen: @mees- , also @Ragg-

**Comment by shinnn** [comment]
Yes, I assume Github used to allow the last hyphen [at least until 2013](https://github.com/mees-?tab=overview&from=2013-05-01&to=2013-05-31#contribution-joined-github-4339375-2013-05-04), but currently it doesn't.

![image](https://user-images.githubusercontent.com/1131567/29600484-235801c4-8811-11e7-8d3e-b8134052541a.png)

This library follows current rules of the signup form validation.

**Comment by shinnn** [comment]
Documentation update would fix this issue. For example,

```diff
- A regular expression that only matches a valid Github username
+ A regular expression that only matches a currently valid Github username
```

Or, any other ideas are welcomed.

**Comment by shinnn** [comment]
No feedback.

**Comment by Lanchon** [comment]
other examples:
https://github.com/artur-
https://github.com/ArtOfCode-

your regex doesn't allow matching existing grandfathered usernames in mentions like @artur- (sorry artur-), while github clearly supports this.

your repo confounds the issue for coders needing a regex by promoting the idea that a single regex is enough, while in reality two regex are needed:
1. one that matches any existing username
2. another that validates usernames that could be created today

you are providing only # 2, and i can't think of much use for it. # 1 is what coders usually need.

**Comment by shinnn** [comment]
I disagree.
